language: python
os:
  - osx
python:
  - "2.7.13"
before_install:
  - brew update  
  - brew install opencv  
  - brew install boost  
  - brew install portaudio  
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover