language: python
python:
  - "2.7"
before_install:
  - brew update  
  - brew install opencv  
  - brew install boost  
  - brew install portaudio  
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover